---
local:
  hosts:
    localhost:

arch:
  hosts:
    hecate:


dnf5:
  hosts:
    minime:

flatpak:
  hosts:
    minime:
    hecate:

# docker_hosts:
#   hosts:
#     koffing
#     scyther
#     scizor
#     rpi3 docker_install_compose=false

# gui:
#   hosts:
#     steelix
#     scyther
#     blastoise
#     charmander
#     scizor
#     koffing
#
# work:
#   hosts:
#     scyther
#     blastoise
#     charmander
#
# stream_host:
#   hosts:
#     blastoise
#     squirtle
#     charmander
#
# amd_firmware:
#   hosts:
#     charmander
#
# log_collection:
#   hosts:
#     scyther
#     scizor
#     steelix
#     squirtle
#     blastoise
#     charmander
#     koffing
#     doduo
#     dodrio
#     ditto
#     rpi3
#     eevee
#     vaporeon
#     jolteon

# ansible_pull_managed:
#   hosts:
#     hecate
#     squirtle
#     blastoise
#     charmander
#     koffing
#     steelix
#     doduo
#     dodrio
#     ditto
#     rpi3
